proxies:
- alpn: []
  name: 13|🇭🇰 香港|@ripaojiedian
  network: tcp
  password: ouo
  port: 443
  server: 103.44.255.81
  sni: tr.koxok.us.kg
  tls: 'true'
  type: trojan
- alterId: 64
  cipher: auto
  name: 13|🇭🇰 香港2|@ripaojiedian
  network: tcp
  port: 48109
  server: 183.236.51.23
  tls: ''
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  ws-opts:
    headers:
      Host: ''
    path: ''
- alterId: 64
  cipher: auto
  name: 13|🇭🇰 香港3|@ripaojiedian
  network: tcp
  port: 54104
  server: 183.236.51.23
  tls: ''
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  ws-opts:
    headers:
      Host: ''
    path: ''
- alpn: []
  name: 13,14|香港4|@ripaojiedian
  network: tcp
  password: 9e2a92c6-bbe6-49fa-a280-e6f8f3eed7c5
  port: 27886
  server: zhk5.capoonetwork.com
  sni: www.bilibili.com
  tls: 'true'
  type: trojan
- alterId: 64
  cipher: auto
  name: 13|🇭🇰 香港6|@ripaojiedian
  network: tcp
  port: 44614
  server: 120.198.71.219
  tls: ''
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  ws-opts:
    headers:
      Host: ''
    path: ''
- alterId: 0
  cipher: auto
  name: 13|🇯🇵 日本|@ripaojiedian
  network: tcp
  port: 19690
  server: ywtwepcnwlou.xn--fiqs8sjz2bull.com
  tls: ''
  type: vmess
  uuid: 38eda6f2-6e04-4484-8f82-e859e76612d6
  ws-opts:
    headers:
      Host: ''
    path: ''
- alpn: []
  name: 13|🇯🇵 日本2|@ripaojiedian
  network: tcp
  password: ouo
  port: 443
  server: 154.83.91.150
  sni: tr.koxok.us.kg
  tls: 'true'
  type: trojan
- alpn: []
  name: 13|🇰🇷 韩国|@ripaojiedian
  network: tcp
  password: ouo
  port: 40274
  server: 132.226.171.151
  sni: tr.koxok.us.kg
  tls: 'true'
  type: trojan
- alterId: 0
  cipher: auto
  name: 13|🇸🇬 新加坡2|@ripaojiedian
  network: tcp
  port: 53896
  server: pudvkjvvgdol.xn--fiqs8sjz2bull.com
  tls: ''
  type: vmess
  uuid: 38eda6f2-6e04-4484-8f82-e859e76612d6
  ws-opts:
    headers:
      Host: ''
    path: ''
- alpn: []
  name: 13,14|新加坡3|@ripaojiedian
  network: tcp
  password: 9e2a92c6-bbe6-49fa-a280-e6f8f3eed7c5
  port: 23570
  server: zsg2.capoonetwork.com
  sni: v.qq.com
  tls: 'true'
  type: trojan
- alterId: 0
  cipher: auto
  name: 13|🇺🇸 美国|@ripaojiedian
  network: tcp
  port: 46833
  server: 38.147.161.252
  tls: ''
  type: vmess
  uuid: 77175906-b651-4c44-9397-04b30a602c0c
  ws-opts:
    headers:
      Host: ''
    path: ''
- alpn: []
  name: 13,14|美国2|@ripaojiedian
  network: tcp
  password: 2b39bbdd-a565-4f8e-b6b6-6b034b2076f4
  port: 13021
  server: naiu-us.05vr9nyqg5.download
  sni: cloudflare.node-ssl.cdn-alibaba.com
  tls: 'true'
  type: trojan
- alterId: 0
  cipher: auto
  name: 13|🇩🇪 德国|@ripaojiedian
  network: tcp
  port: 2082
  server: 64.225.109.206
  tls: ''
  type: vmess
  uuid: 48264b45-64b8-4e9f-8a88-cef41f20c736
  ws-opts:
    headers:
      Host: ''
    path: ''
- alpn: []
  name: 14|香港|@ripaojiedian
  network: tcp
  password: ouo
  port: 443
  server: 103.44.255.81
  sni: tr.koxok.us.kg
  tls: 'true'
  type: trojan
- alterId: 64
  cipher: auto
  name: 14|香港2|@ripaojiedian
  network: tcp
  port: 48109
  server: 183.236.51.23
  tls: ''
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  ws-opts:
    headers:
      Host: ''
    path: ''
- alterId: 64
  cipher: auto
  name: 14|香港3|@ripaojiedian
  network: tcp
  port: 54104
  server: 183.236.51.23
  tls: ''
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  ws-opts:
    headers:
      Host: ''
    path: ''
- alterId: 64
  cipher: auto
  name: 14|香港6|@ripaojiedian
  network: tcp
  port: 44614
  server: 120.198.71.219
  tls: ''
  type: vmess
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  ws-opts:
    headers:
      Host: ''
    path: ''
- alterId: 0
  cipher: auto
  name: 14|日本|@ripaojiedian
  network: tcp
  port: 19690
  server: ywtwepcnwlou.xn--fiqs8sjz2bull.com
  tls: ''
  type: vmess
  uuid: 38eda6f2-6e04-4484-8f82-e859e76612d6
  ws-opts:
    headers:
      Host: ''
    path: ''
- alpn: []
  name: 14|日本2|@ripaojiedian
  network: tcp
  password: ouo
  port: 443
  server: 154.83.91.150
  sni: tr.koxok.us.kg
  tls: 'true'
  type: trojan
- alpn: []
  name: 14|韩国|@ripaojiedian
  network: tcp
  password: ouo
  port: 40274
  server: 132.226.171.151
  sni: tr.koxok.us.kg
  tls: 'true'
  type: trojan
- alterId: 0
  cipher: auto
  name: 14|新加坡2|@ripaojiedian
  network: tcp
  port: 53896
  server: pudvkjvvgdol.xn--fiqs8sjz2bull.com
  tls: ''
  type: vmess
  uuid: 38eda6f2-6e04-4484-8f82-e859e76612d6
  ws-opts:
    headers:
      Host: ''
    path: ''
- alterId: 0
  cipher: auto
  name: 14|美国|@ripaojiedian
  network: tcp
  port: 46833
  server: 38.147.161.252
  tls: ''
  type: vmess
  uuid: 77175906-b651-4c44-9397-04b30a602c0c
  ws-opts:
    headers:
      Host: ''
    path: ''
- alterId: 0
  cipher: auto
  name: 14|德国|@ripaojiedian
  network: tcp
  port: 2082
  server: 64.225.109.206
  tls: ''
  type: vmess
  uuid: 48264b45-64b8-4e9f-8a88-cef41f20c736
  ws-opts:
    headers:
      Host: ''
    path: ''
- alpn:
  - h2
  headers:
    type: none
  name: 15|AR_speednode_0001
  network: tcp
  port: 8443
  security: tls
  server: eze-1.fromblancwithlove.com
  sni: ''
  type: vless
  uuid: 157448af-8ecf-4075-a9e9-b23a6a94899b
- alpn:
  - h2
  headers:
    type: none
  name: 15|AR_speednode_0002
  network: tcp
  port: 8443
  security: tls
  server: 103.50.33.138
  sni: eze-1.fromblancwithlove.com
  type: vless
  uuid: 157448af-8ecf-4075-a9e9-b23a6a94899b
- alpn:
  - h2
  headers:
    type: none
  name: 15|BE_speednode_0003
  network: tcp
  port: 8443
  security: tls
  server: 79.127.224.12
  sni: bru-be-01.fromblancwithlove.com
  type: vless
  uuid: 157448af-8ecf-4075-a9e9-b23a6a94899b
- alpn:
  - h2
  headers:
    type: none
  name: 15|BR_speednode_0004
  network: tcp
  port: 8443
  security: tls
  server: 46.151.194.89
  sni: sao-br.fromblancwithlove.com
  type: vless
  uuid: 157448af-8ecf-4075-a9e9-b23a6a94899b
- alpn:
  - h2
  headers:
    type: none
  name: 15|BR_speednode_0005
  network: tcp
  port: 8443
  security: tls
  server: sao-br.fromblancwithlove.com
  sni: ''
  type: vless
  uuid: 157448af-8ecf-4075-a9e9-b23a6a94899b
- alpn:
  - h2
  headers:
    type: none
  name: 15|CO_speednode_0016
  network: tcp
  port: 8443
  security: tls
  server: 169.150.228.24
  sni: bog-co-01.fromblancwithlove.com
  type: vless
  uuid: 157448af-8ecf-4075-a9e9-b23a6a94899b
- alpn:
  - h2
  headers:
    type: none
  name: 15|CO_speednode_0017
  network: tcp
  port: 8443
  security: tls
  server: bog-co-01.fromblancwithlove.com
  sni: ''
  type: vless
  uuid: 157448af-8ecf-4075-a9e9-b23a6a94899b
- alpn:
  - h2
  headers:
    type: none
  name: 15|DE_speednode_0020
  network: tcp
  port: 8443
  security: tls
  server: 195.181.175.176
  sni: de1.fromblancwithlove.com
  type: vless
  uuid: 157448af-8ecf-4075-a9e9-b23a6a94899b
- alpn:
  - http/1.1
  headers:
    type: none
  name: 15|DE_speednode_0025
  network: tcp
  port: 443
  security: tls
  server: 156.67.30.77
  sni: spotify.com
  type: vless
  uuid: 1051bfbb-90db-4261-b5e4-8b91f62b436f
- alpn:
  - h2
  headers:
    type: none
  name: 15|ES_speednode_0026
  network: tcp
  port: 8443
  security: tls
  server: 212.102.48.216
  sni: mad-es.fromblancwithlove.com
  type: vless
  uuid: 157448af-8ecf-4075-a9e9-b23a6a94899b
- alpn:
  - h2
  headers:
    type: none
  name: 15|ES_speednode_0027
  network: tcp
  port: 8443
  security: tls
  server: mad-es.fromblancwithlove.com
  sni: ''
  type: vless
  uuid: 157448af-8ecf-4075-a9e9-b23a6a94899b
- alpn: []
  headers:
    type: none
  name: 15|FR_speednode_0028
  network: tcp
  port: 22671
  security: none
  server: 91.134.102.128
  sni: telewebion.com
  type: vless
  uuid: 91989253-37d6-4d28-83fe-8ffd0c3de0f7
- alpn:
  - h2
  headers:
    type: none
  name: 15|GB_speednode_0030
  network: tcp
  port: 8443
  security: tls
  server: 95.173.205.70
  sni: osl-no-01.fromblancwithlove.com
  type: vless
  uuid: 157448af-8ecf-4075-a9e9-b23a6a94899b
- alpn:
  - h2
  headers:
    type: none
  name: 15|GR_speednode_0031
  network: tcp
  port: 8443
  security: tls
  server: ath-gr-01.fromblancwithlove.com
  sni: ''
  type: vless
  uuid: 157448af-8ecf-4075-a9e9-b23a6a94899b
- alpn:
  - h2
  headers:
    type: none
  name: 15|GR_speednode_0032
  network: tcp
  port: 8443
  security: tls
  server: 79.127.218.204
  sni: ath-gr-01.fromblancwithlove.com
  type: vless
  uuid: 157448af-8ecf-4075-a9e9-b23a6a94899b
- alpn:
  - h2
  headers:
    type: none
  name: 15|IN_speednode_0034
  network: tcp
  port: 8443
  security: tls
  server: 64.227.148.121
  sni: blr-in.fromblancwithlove.com
  type: vless
  uuid: 157448af-8ecf-4075-a9e9-b23a6a94899b
- alpn:
  - h2
  headers:
    type: none
  name: 15|KZ_speednode_0037
  network: tcp
  port: 8443
  security: tls
  server: kz-2.fromblancwithlove.com
  sni: ''
  type: vless
  uuid: 157448af-8ecf-4075-a9e9-b23a6a94899b
- alpn:
  - h2
  headers:
    type: none
  name: 15|PE_speednode_0038
  network: tcp
  port: 8443
  security: tls
  server: lim-pe-01.fromblancwithlove.com
  sni: ''
  type: vless
  uuid: 157448af-8ecf-4075-a9e9-b23a6a94899b
- alpn:
  - h2
  headers:
    type: none
  name: 15|PE_speednode_0039
  network: tcp
  port: 8443
  security: tls
  server: 79.127.252.81
  sni: lim-pe-01.fromblancwithlove.com
  type: vless
  uuid: 157448af-8ecf-4075-a9e9-b23a6a94899b
- alpn: []
  headers:
    type: none
  name: 15|RU_speednode_0042
  network: ws
  port: 443
  security: none
  server: 46.254.92.33
  sni: mmdserver.us.kg
  type: vless
  uuid: 41abecd9-8096-4142-a75c-4e1d36d990bd
- alpn:
  - h2
  headers:
    type: none
  name: 15|SG_speednode_0044
  network: tcp
  port: 8443
  security: tls
  server: 156.146.56.207
  sni: sin-sg-01.fromblancwithlove.com
  type: vless
  uuid: 157448af-8ecf-4075-a9e9-b23a6a94899b
- alpn:
  - h2
  headers:
    type: none
  name: 15|SG_speednode_0045
  network: tcp
  port: 8443
  security: tls
  server: sin-sg-01.fromblancwithlove.com
  sni: ''
  type: vless
  uuid: 157448af-8ecf-4075-a9e9-b23a6a94899b
- alpn: []
  headers:
    type: none
  name: 15|US_speednode_0047
  network: ws
  port: 443
  security: none
  server: 192.0.54.235
  sni: mmdserver.us.kg
  type: vless
  uuid: 41abecd9-8096-4142-a75c-4e1d36d990bd
- alpn:
  - h2
  headers:
    type: none
  name: 15|ZA_speednode_0049
  network: tcp
  port: 8443
  security: tls
  server: jnb-sa.fromblancwithlove.com
  sni: ''
  type: vless
  uuid: 157448af-8ecf-4075-a9e9-b23a6a94899b
- alpn:
  - h2
  headers:
    type: none
  name: 15|ZA_speednode_0050
  network: tcp
  port: 8443
  security: tls
  server: 169.150.246.91
  sni: jnb-sa.fromblancwithlove.com
  type: vless
  uuid: 157448af-8ecf-4075-a9e9-b23a6a94899b
- alterId: 0
  cipher: auto
  name: 16|d*********g.com_2
  network: tcp
  port: 443
  server: 42.236.73.72
  tls: tls
  type: vmess
  uuid: 044f0177-0675-4dcf-89d4-804b6788e518
  ws-opts:
    headers:
      Host: ''
    path: ''
- alpn:
  - http/1.1
  headers:
    type: none
  name: 16|d*********g.com_6
  network: tcp
  port: 443
  security: tls
  server: 42.236.73.72
  sni: www.zitian.cn
  type: vless
  uuid: 11916472-4e2c-49c6-b75d-71196b3a7ecf
- alpn:
  - http/1.1
  name: 16|d*********g.com_3
  network: tcp
  password: fuck
  port: 443
  server: 42.236.73.72
  sni: www.zitian.cn
  tls: 'true'
  type: trojan
proxy-groups:
- name: 🚀 节点选择
  proxies:
  - DIRECT
  - 13|🇭🇰 香港|@ripaojiedian
  - 13|🇭🇰 香港2|@ripaojiedian
  - 13|🇭🇰 香港3|@ripaojiedian
  - 13,14|香港4|@ripaojiedian
  - 13|🇭🇰 香港6|@ripaojiedian
  - 13|🇯🇵 日本|@ripaojiedian
  - 13|🇯🇵 日本2|@ripaojiedian
  - 13|🇰🇷 韩国|@ripaojiedian
  - 13|🇸🇬 新加坡2|@ripaojiedian
  - 13,14|新加坡3|@ripaojiedian
  - 13|🇺🇸 美国|@ripaojiedian
  - 13,14|美国2|@ripaojiedian
  - 13|🇩🇪 德国|@ripaojiedian
  - 14|香港|@ripaojiedian
  - 14|香港2|@ripaojiedian
  - 14|香港3|@ripaojiedian
  - 14|香港6|@ripaojiedian
  - 14|日本|@ripaojiedian
  - 14|日本2|@ripaojiedian
  - 14|韩国|@ripaojiedian
  - 14|新加坡2|@ripaojiedian
  - 14|美国|@ripaojiedian
  - 14|德国|@ripaojiedian
  - 15|AR_speednode_0001
  - 15|AR_speednode_0002
  - 15|BE_speednode_0003
  - 15|BR_speednode_0004
  - 15|BR_speednode_0005
  - 15|CO_speednode_0016
  - 15|CO_speednode_0017
  - 15|DE_speednode_0020
  - 15|DE_speednode_0025
  - 15|ES_speednode_0026
  - 15|ES_speednode_0027
  - 15|FR_speednode_0028
  - 15|GB_speednode_0030
  - 15|GR_speednode_0031
  - 15|GR_speednode_0032
  - 15|IN_speednode_0034
  - 15|KZ_speednode_0037
  - 15|PE_speednode_0038
  - 15|PE_speednode_0039
  - 15|RU_speednode_0042
  - 15|SG_speednode_0044
  - 15|SG_speednode_0045
  - 15|US_speednode_0047
  - 15|ZA_speednode_0049
  - 15|ZA_speednode_0050
  - 16|d*********g.com_2
  - 16|d*********g.com_6
  - 16|d*********g.com_3
  type: select
- name: 🚀 手动切换
  proxies:
  - ♻️ Auto
  - 13|🇭🇰 香港|@ripaojiedian
  - 13|🇭🇰 香港2|@ripaojiedian
  - 13|🇭🇰 香港3|@ripaojiedian
  - 13,14|香港4|@ripaojiedian
  - 13|🇭🇰 香港6|@ripaojiedian
  - 13|🇯🇵 日本|@ripaojiedian
  - 13|🇯🇵 日本2|@ripaojiedian
  - 13|🇰🇷 韩国|@ripaojiedian
  - 13|🇸🇬 新加坡2|@ripaojiedian
  - 13,14|新加坡3|@ripaojiedian
  - 13|🇺🇸 美国|@ripaojiedian
  - 13,14|美国2|@ripaojiedian
  - 13|🇩🇪 德国|@ripaojiedian
  - 14|香港|@ripaojiedian
  - 14|香港2|@ripaojiedian
  - 14|香港3|@ripaojiedian
  - 14|香港6|@ripaojiedian
  - 14|日本|@ripaojiedian
  - 14|日本2|@ripaojiedian
  - 14|韩国|@ripaojiedian
  - 14|新加坡2|@ripaojiedian
  - 14|美国|@ripaojiedian
  - 14|德国|@ripaojiedian
  - 15|AR_speednode_0001
  - 15|AR_speednode_0002
  - 15|BE_speednode_0003
  - 15|BR_speednode_0004
  - 15|BR_speednode_0005
  - 15|CO_speednode_0016
  - 15|CO_speednode_0017
  - 15|DE_speednode_0020
  - 15|DE_speednode_0025
  - 15|ES_speednode_0026
  - 15|ES_speednode_0027
  - 15|FR_speednode_0028
  - 15|GB_speednode_0030
  - 15|GR_speednode_0031
  - 15|GR_speednode_0032
  - 15|IN_speednode_0034
  - 15|KZ_speednode_0037
  - 15|PE_speednode_0038
  - 15|PE_speednode_0039
  - 15|RU_speednode_0042
  - 15|SG_speednode_0044
  - 15|SG_speednode_0045
  - 15|US_speednode_0047
  - 15|ZA_speednode_0049
  - 15|ZA_speednode_0050
  - 16|d*********g.com_2
  - 16|d*********g.com_6
  - 16|d*********g.com_3
  type: select
- name: ♻️ Auto
  proxies:
  - DIRECT
  - 13|🇭🇰 香港|@ripaojiedian
  - 13|🇭🇰 香港2|@ripaojiedian
  - 13|🇭🇰 香港3|@ripaojiedian
  - 13,14|香港4|@ripaojiedian
  - 13|🇭🇰 香港6|@ripaojiedian
  - 13|🇯🇵 日本|@ripaojiedian
  - 13|🇯🇵 日本2|@ripaojiedian
  - 13|🇰🇷 韩国|@ripaojiedian
  - 13|🇸🇬 新加坡2|@ripaojiedian
  - 13,14|新加坡3|@ripaojiedian
  - 13|🇺🇸 美国|@ripaojiedian
  - 13,14|美国2|@ripaojiedian
  - 13|🇩🇪 德国|@ripaojiedian
  - 14|香港|@ripaojiedian
  - 14|香港2|@ripaojiedian
  - 14|香港3|@ripaojiedian
  - 14|香港6|@ripaojiedian
  - 14|日本|@ripaojiedian
  - 14|日本2|@ripaojiedian
  - 14|韩国|@ripaojiedian
  - 14|新加坡2|@ripaojiedian
  - 14|美国|@ripaojiedian
  - 14|德国|@ripaojiedian
  - 15|AR_speednode_0001
  - 15|AR_speednode_0002
  - 15|BE_speednode_0003
  - 15|BR_speednode_0004
  - 15|BR_speednode_0005
  - 15|CO_speednode_0016
  - 15|CO_speednode_0017
  - 15|DE_speednode_0020
  - 15|DE_speednode_0025
  - 15|ES_speednode_0026
  - 15|ES_speednode_0027
  - 15|FR_speednode_0028
  - 15|GB_speednode_0030
  - 15|GR_speednode_0031
  - 15|GR_speednode_0032
  - 15|IN_speednode_0034
  - 15|KZ_speednode_0037
  - 15|PE_speednode_0038
  - 15|PE_speednode_0039
  - 15|RU_speednode_0042
  - 15|SG_speednode_0044
  - 15|SG_speednode_0045
  - 15|US_speednode_0047
  - 15|ZA_speednode_0049
  - 15|ZA_speednode_0050
  - 16|d*********g.com_2
  - 16|d*********g.com_6
  - 16|d*********g.com_3
  type: select
- name: 🌍 国外媒体
  proxies:
  - DIRECT
  - 13|🇭🇰 香港|@ripaojiedian
  - 13|🇭🇰 香港2|@ripaojiedian
  - 13|🇭🇰 香港3|@ripaojiedian
  - 13,14|香港4|@ripaojiedian
  - 13|🇭🇰 香港6|@ripaojiedian
  - 13|🇯🇵 日本|@ripaojiedian
  - 13|🇯🇵 日本2|@ripaojiedian
  - 13|🇰🇷 韩国|@ripaojiedian
  - 13|🇸🇬 新加坡2|@ripaojiedian
  - 13,14|新加坡3|@ripaojiedian
  - 13|🇺🇸 美国|@ripaojiedian
  - 13,14|美国2|@ripaojiedian
  - 13|🇩🇪 德国|@ripaojiedian
  - 14|香港|@ripaojiedian
  - 14|香港2|@ripaojiedian
  - 14|香港3|@ripaojiedian
  - 14|香港6|@ripaojiedian
  - 14|日本|@ripaojiedian
  - 14|日本2|@ripaojiedian
  - 14|韩国|@ripaojiedian
  - 14|新加坡2|@ripaojiedian
  - 14|美国|@ripaojiedian
  - 14|德国|@ripaojiedian
  - 15|AR_speednode_0001
  - 15|AR_speednode_0002
  - 15|BE_speednode_0003
  - 15|BR_speednode_0004
  - 15|BR_speednode_0005
  - 15|CO_speednode_0016
  - 15|CO_speednode_0017
  - 15|DE_speednode_0020
  - 15|DE_speednode_0025
  - 15|ES_speednode_0026
  - 15|ES_speednode_0027
  - 15|FR_speednode_0028
  - 15|GB_speednode_0030
  - 15|GR_speednode_0031
  - 15|GR_speednode_0032
  - 15|IN_speednode_0034
  - 15|KZ_speednode_0037
  - 15|PE_speednode_0038
  - 15|PE_speednode_0039
  - 15|RU_speednode_0042
  - 15|SG_speednode_0044
  - 15|SG_speednode_0045
  - 15|US_speednode_0047
  - 15|ZA_speednode_0049
  - 15|ZA_speednode_0050
  - 16|d*********g.com_2
  - 16|d*********g.com_6
  - 16|d*********g.com_3
  type: select
rules:
- RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list,🎯
  全球直连
- RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.list,🎯
  全球直连
- RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list,🛑
  全球拦截
- RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list,🍃
  应用净化
- RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list,🎯
  全球直连
- RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list,🎯
  全球直连
- RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing.list,Ⓜ️
  Copilot
- RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Copilot/Copilot.list,Ⓜ️
  Copilot
- RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list,Ⓜ️
  微软服务
- RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.list,🍎
  苹果服务
- RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list,📲
  Telegram
- RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list,💬
  OpenAi
- RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.list,💬
  OpenAi
- RULE-SET,https://raw.githubusercontent.com/coco-yan/proxy_ruleset/dev/rule_addition.list,💬
  OpenAi
- RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list,🎥
  Netflix
- RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.list,🌍
  国外媒体
- RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list,🚀
  节点选择
- RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list,🎯
  全球直连
- RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list,🎯
  全球直连
- RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.list,🎯
  全球直连
- GEOIP,CN,🎯 全球直连
- FINAL,🐟 漏网之鱼
