jobs:
  openwrt-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install QEMU run openwrt
        run: sudo apt update && sudo apt install -y qemu-system-x86

      - name: Download OpenWrt Image
        run: wget https://downloads.openwrt.org/releases/23.05.0/targets/x86/64/openwrt-23.05.0-x86-64-generic-ext4-combined.img.gz

      - name: Extract Image
        run: gunzip openwrt-23.05.0-x86-64-generic-ext4-combined.img.gz

      - name: Run OpenWrt in QEMU
        run: |
          qemu-system-x86_64 -nographic -m 512M \
            -drive file=openwrt-23.05.0-x86-64-generic-ext4-combined.img,format=raw \
            -kernel bzImage -append "console=ttyS0" &