name: Actions-down-v2ray

on:
  workflow_dispatch:   # 手动触发
  schedule:
    - cron: '0 */8 * * *'  # 8小时一次

jobs:
  update_yaml_configs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 创建配置文件目录
        run: |
          echo "Cleaning up old configs"
          rm -rf ./configs
          mkdir -p ./configs
          echo "Configs directory created"

      - name: 安装 wget（如果未安装）
        run: |
          if ! command -v wget &> /dev/null
          then
            apt-get install -y wget
          fi

      - name: 下载 Base64 编码的 TXT 文件
        run: |
          V2RAY_URL1="https://little-thunder-d99c.linzf5039.workers.dev/335581?b64"
          V2RAY_URL2="https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/v.txt"
          CURRENT_DATE=$(date +'%Y%m%d') # 验证格式是否正确
          V2RAY_URL3="https://clashgithub.com/wp-content/uploads/rss/${CURRENT_DATE}.txt"
          curl -fLo ./configs/config1.txt "$V2RAY_URL1" || echo "Failed to download config1.txt"
          curl -fLo ./configs/config2.txt "$V2RAY_URL2" || echo "Failed to download config2.txt"
          curl -fLo ./configs/config3.txt "$V2RAY_URL3" || echo "Failed to download config3.txt"

      - name: 安装 Python 3 和依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install requests pyyaml    

      - name: Base64 转v2ray 合并一个 TXT 文件
        run: |
           python3 decode_base64_to_v2ray.py
        
      - name: v2ray转clash
        run: |
           python3 convert_v2ray_to_clash.py
        
      - name: 添加文件目录到 Git
        run: |
          git config --global user.email "senina8866@gmail.com"
          git config --global user.name "senina8866"
          git add -f ./configs
          git commit -m "Add Files to configs" || echo "No changes to commit"
          git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:main
