name: mkdir Configs

on:
  workflow_dispatch:   # 手动触发
  schedule:
    - cron: '0 0 * * *'  # 每天午夜触发

jobs:
  update_yaml_configs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 创建配置文件目录
        run: |
          echo "Before creating configs directory"
          mkdir -p ./configs
          echo "Configs directory created"

      - name: List files
        run: |
          ls -la
