name: merge clash yaml

on:
  workflow_dispatch:   # 手动触发
  schedule:
    - cron: '* */2 * * *'  # 2小时一次

jobs:
  update_yaml_configs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check space usage
        if: (!cancelled())
        run: cat /proc/cpuinfo && cat /proc/meminfo && df -hT
        
      - name: 创建配置文件目录
        run: |
          echo "Before creating configs directory"
          mkdir -p ./configs
          echo "Configs directory created"
          
      - name: 安装 wget（如果未安装）
        run: |
          if ! command -v wget &> /dev/null
          then
            sudo apt-get install -y wget
          fi

      - name: 下载 YAML 配置文件
        run: |
          YAML_URL1="https://little-thunder-d99c.linzf5039.workers.dev/335581?clash"
          YAML_URL2="https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml"
          wget -O ./configs/config1.yaml $YAML_URL1
          wget -O ./configs/config2.yaml $YAML_URL2

      - name: 安装 Python 3 和依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install pyyaml    

      - name: 合并YAML
        run: |
          python3 merge_yaml.py
          
      - name: 添加目录到 Git
        run: |
            git config --global user.email "senina8866@gmail.com"
            git config --global user.name "senina8866"
            git add -f ./configs
            #git add -f ./configs/config1.yaml
            #git add -f ./configs/config2.yaml
            git commit -m "Add configs directory"
            git push
