name: mkdir Configs

on:
  workflow_dispatch:   # 手动触发
  schedule:

jobs:
  update_yaml_configs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 

      - name: 创建配置文件目录
        run: |
          mkdir -p ./configs


