name: mkdir Configs 1

on:
  workflow_dispatch:   # 手动触发
  schedule:
    - cron: '0 0 * * *'  # 每天午夜触发

jobs:
  update_yaml_configs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 创建配置文件目录
        run: |
          echo "Before creating configs directory"
          mkdir -p ./configs
          echo "Configs directory created"

      - name: 添加目录到 Git
        run: |
            git config --global user.email "senina8866@gmail.com"
            git config --global user.name "senina8866"
            git add -f ./configs
            git commit -m "Add configs directory"
            git push
