name: Update YAML Configs

on:
  workflow_dispatch:   # 手动触发
  schedule:
    # 每小时执行一次
    - cron: "0 */1 * * *"
  push:
    branches:
      - main

jobs:
  update_yaml_configs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 安装 wget（如果未安装）
        run: |
          if ! command -v wget &> /dev/null
          then
            sudo apt-get install -y wget
          fi

      - name: 安装 Python 3 和依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install pyyaml    

      - name: 创建配置文件目录
        run: |
          mkdir -p ./configs

      - name: 下载 YAML 配置文件
        run: |
          YAML_URL1="https://little-thunder-d99c.linzf5039.workers.dev/335581?clash"
          YAML_URL2="https://raw.githubusercontent.com/free18/v2ray/refs/heads/main/c.yaml"
          wget -O ./configs/config1.yaml $YAML_URL1
          wget -O ./configs/config2.yaml $YAML_URL2
